language: android
jdk: oraclejdk8
sudo: false

env:
  global:
    - ANDROID_API_LEVEL=27
    - ANDROID_BUILD_TOOLS_VERSION=27.1.0

android:
  components:
      - tools
      - platform-tools
      - build-tools-$ANDROID_BUILD_TOOLS_VERSION
      - extra
      - android-$ANDROID_API_LEVEL

  licenses:
        - android-sdk-license-.+
        - '.+'

notifications:
  email: false

script:
  - ./gradlew assembleRelease
